"""To and Fromroutes

Revision ID: a47629d5ad3c
Revises: 907ede9189e0
Create Date: 2024-05-14 00:37:54.623405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47629d5ad3c'
down_revision = '907ede9189e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_route', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('to_route', sa.String(length=100), nullable=False))
        batch_op.alter_column('departure_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('arrival_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('route')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('arrival_time',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('departure_time',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('to_route')
        batch_op.drop_column('from_route')

    # ### end Alembic commands ###
